### ISSUE TITLE
Mechanism to load private Rōblox custom audio

### ISSUE THREAD

**Issue by LazVaz12** [Windows81/Roblox-Freedom-Distribution#67]
I've been playing for a while and I've noticed about 4 bugs:
1. Even if set in the config, gamepasses act as developer products and also do not work. (You can buy them over and over + they won't work (Only tested on 2018)
2. R15 Idle animation keeps glitching (Only tested on 2018)
3. User Generated animations + audios that are private do not load, there is infact a way to load them which some people use (A Harmless Roblox Community server) that works to download almost all privated assets (I would love to have that implimented.
Those are all the bugs, also I hope to see 2017-2021 clients one day!

<img alt="67" src="https://github.com/user-attachments/assets/752bb0bc-fdde-4224-9468-30741b38c3bc" />

**Comment by LazVaz12** [comment]
It is a discord server which has a bot that can upload stuff, there is also an asset reuploader tool that uses cookies but I am unsure if it is safe (seems to be open source, https://github.com/kartFr/Asset-Reuploader) For the discord server with the animation and audio bot: https://discord.gg/j86sZbf5 Hopefully you can contact the owner of the discord bot if the asset reuploader isn't safe.

**Comment by LazVaz12** [comment]
@Windows81 Also, another suggestion is a way to have players load in their own avatar config (only asset ids and rig type, the player's rig type will be forced based off the server unless you set it to "PlayerChoice" or someting like that.

**Comment by Windows81** [comment]
I recall seeing a tool which lets you download audio and animations just with a cookie and a place iden.  Might post it here when I find it.

**Comment by LazVaz12** [comment]
@Windows81 That is the https://github.com/kartFr/Asset-Reuploader one, if you click the newest release in the description it says that you need a place id (you obviously need a cookie too). It also says that it doesn't require the cookie on some assets.

**Comment by Windows81** [comment]
Dev products should be fixed in 2018.  Try them out now.

**Comment by Windows81** [comment]
To modify your robux amount, use a SQLite editor.  Your default database location should be in the same place as the GameConfig file.

**Comment by eixxom1** [comment]
> It is a discord server which has a bot that can upload stuff, there is also an asset reuploader tool that uses cookies but I am unsure if it is safe (seems to be open source, https://github.com/kartFr/Asset-Reuploader) For the discord server with the animation and audio bot: https://discord.gg/j86sZbf5 Hopefully you can contact the owner of the discord bot if the asset reuploader isn't safe.

That discord server is not needed, you can just download it on the roblox site. Same for animations. You cant download place files i think. Also to download stuff manually, idk if you need some betterblox, ropro, or whatever extension just use this

`https://assetdelivery.roblox.com/v1/asset/?id=X`

The ID of the song or animation you want to download, put that where `X` is, shouldnt have to explain this.

For importing audio, it just needs to be in OGG format but just remove the file extension so its just the id, and put it into AssetCache, No idea if this is supost to how you should do it, but it works. _OGG File format IIRC_

There is no need for that discord server other then people not knowing how to do what i said above.

<img width="1649" height="749" alt="Image" src="https://github.com/user-attachments/assets/ba33ba43-0b80-4ce4-a429-75f78e9686d1" /> 

<img width="766" height="211" alt="Image" src="https://github.com/user-attachments/assets/f6ed54d7-615e-4e45-8fbc-d2664e75fd55" />
There is no need for that discord server other then people not knowing how to do what i said above

**Comment by LazVaz12** [comment]
@Windows81 Modified my database and gave myself enough, still doesn't work. Unsure why gamepasses don't work

**Comment by LazVaz12** [comment]
@Windows81 I am unsure how I can use the studio, do i do --run_studio or something?

**Comment by LazVaz12** [comment]
I tried out the studio, it's alright. It doesn't do the cookie loading thing but I assume its difficult to do on studio. Also, is there a way where I can manually download animations and put them in the cache?

**Comment by LazVaz12** [comment]
@eixxom1 I think 2017-2021 would be nice, I feel like a 2017M and 2020E would be nice, 2020E when it was the old chat stuff but the new leaderboard. 2017M For most games as it launches best.

**Comment by Windows81** [comment]
@LazVaz12: just change:
```
rfd server -c "PATH_TO_CONFIG" ...
```

...to...

```
rfd studio -c "PATH_TO_CONFIG"
```

The correct version of Studio will download automatically.

**Comment by Windows81** [comment]
Check out #73.
